import { ExamMeta, MockTest, Question } from "./types";

export const EXAMS: ExamMeta[] = [
  {
    id: "IOE",
    name: "IOE Engineering Entrance",
    description:
      "Institute of Engineering entrance preparation covering Physics, Chemistry, Mathematics and English.",
    subjects: ["Physics", "Chemistry", "Mathematics", "English"],
    totalQuestions: 140,
    durationMinutes: 120,
  },
  {
    id: "CEE",
    name: "CEE Medical Entrance",
    description:
      "Common Entrance Examination preparation for MBBS/BDS covering Physics, Chemistry, Botany, Zoology, and MAT.",
    subjects: ["Physics", "Chemistry", "Botany", "Zoology", "MAT"],
    totalQuestions: 200,
    durationMinutes: 180,
  },
];

// ─── IOE Questions ───────────────────────────────────────────────────────────
const IOE_QUESTIONS: Question[] = [
  {
    id: "ioe-p-1",
    subject: "Physics",
    text: "A body moves with constant acceleration. If its velocity doubles in 4 seconds, what is its acceleration if initial velocity was 5 m/s?",
    options: ["1.0 m/s²", "1.25 m/s²", "2.5 m/s²", "5.0 m/s²"],
    correctIndex: 1,
    explanation: "a = (v - u)/t = (10 - 5)/4 = 1.25 m/s².",
    difficulty: "easy",
    marks: 1,
  },
  {
    id: "ioe-p-2",
    subject: "Physics",
    text: "The dimensional formula of Planck's constant is:",
    options: ["[ML²T⁻¹]", "[ML²T⁻²]", "[MLT⁻¹]", "[ML⁻¹T⁻²]"],
    correctIndex: 0,
    explanation: "E = hν ⇒ h = E/ν has dimensions of angular momentum: [ML²T⁻¹].",
    difficulty: "medium",
    marks: 1,
  },
  {
    id: "ioe-c-1",
    subject: "Chemistry",
    text: "Which of the following is the strongest Brønsted acid?",
    options: ["HF", "HCl", "HBr", "HI"],
    correctIndex: 3,
    explanation: "Acid strength increases down the group: HI is the strongest.",
    difficulty: "easy",
    marks: 1,
  },
  {
    id: "ioe-c-2",
    subject: "Chemistry",
    text: "The hybridisation of carbon in benzene is:",
    options: ["sp", "sp²", "sp³", "sp³d"],
    correctIndex: 1,
    explanation: "Each C in benzene is sp² hybridised with a delocalised π system.",
    difficulty: "easy",
    marks: 1,
  },
  {
    id: "ioe-m-1",
    subject: "Mathematics",
    text: "If f(x) = x² + 2x + 1, then f'(1) equals:",
    options: ["2", "3", "4", "5"],
    correctIndex: 2,
    explanation: "f'(x) = 2x + 2 ⇒ f'(1) = 4.",
    difficulty: "easy",
    marks: 1,
  },
  {
    id: "ioe-m-2",
    subject: "Mathematics",
    text: "The value of ∫₀^π sin(x) dx is:",
    options: ["0", "1", "2", "π"],
    correctIndex: 2,
    explanation: "∫₀^π sin(x)dx = [-cos(x)]₀^π = -(-1) - (-1) = 2.",
    difficulty: "medium",
    marks: 1,
  },
  {
    id: "ioe-e-1",
    subject: "English",
    text: "Choose the word most similar in meaning to 'meticulous':",
    options: ["Careless", "Thorough", "Rapid", "Reluctant"],
    correctIndex: 1,
    explanation: "Meticulous means showing great attention to detail; thorough.",
    difficulty: "easy",
    marks: 1,
  },
  {
    id: "ioe-e-2",
    subject: "English",
    text: "Identify the correct sentence:",
    options: [
      "Neither of the students were present.",
      "Neither of the students was present.",
      "Neither of the student were present.",
      "Neither of the student was present.",
    ],
    correctIndex: 1,
    explanation: "'Neither' takes a singular verb: was.",
    difficulty: "medium",
    marks: 1,
  },
];

// ─── CEE Questions — 180 questions from official exam paper ──────────────────
const CEE_QUESTIONS: Question[] = [
  // ── Physics (50) ──
  { id: "cee-p-1", subject: "Physics", text: "Which of the following have dimension ML²T⁻²:", options: ["Work done", "Pressure", "Stress", "Young's modulus"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-2", subject: "Physics", text: "When earth doesn't rotate about its axis then what effect can be seen in its gravity (except at poles):", options: ["will increase", "will decrease", "remain same", "none"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-3", subject: "Physics", text: "A body is projected with a K.E of K at an angle of 45° with the horizontal. The K.E at maximum height will be:", options: ["0", "k/2", "k", "2k"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-4", subject: "Physics", text: "Two capillary tubes made of same material but different radii were dipped into water:", options: ["liquid rises more in larger radius capillary tube", "liquid rises more in smaller radius capillary tube", "liquid rises equal in both", "no effect"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-5", subject: "Physics", text: "What is the reason for water droplet to be spherical?", options: ["viscosity", "surface tension", "terminal velocity", "pressure"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-6", subject: "Physics", text: "If more than 3 forces are acting on a body in equilibrium, the forces should:", options: ["be collinear", "be coplanar", "form closed polygon", "none of these"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-7", subject: "Physics", text: "The mean density of sea water is d and bulk modulus is B. The change in density at depth h is:", options: ["Bd²/gh", "Bdgh", "d²gh/B", "dgh/B"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-8", subject: "Physics", text: "A thin uniform circular ring rolls down an incline of 30° without slipping. Its linear acceleration along the plane is:", options: ["g/2", "g/4", "g/3", "2g/3"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-9", subject: "Physics", text: "At what condition does the following substance expand on both heating and cooling?", options: ["Water at 0°C", "Water at 4°C", "Ice at 0°C", "Semiconductor"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-10", subject: "Physics", text: "If all the CO₂ is removed, the temperature of earth will:", options: ["be more than present", "be less than present", "depend on average velocity of gas", "may increase or decrease"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-11", subject: "Physics", text: "If the difference in resonating length is 31.5 cm in resonance column, the wavelength produced is:", options: ["31.5 cm", "63.0 cm", "49.0 cm", "101.5 cm"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-12", subject: "Physics", text: "Two tuning forks A and B produce 5 beats/sec. Frequency of A is 512 Hz. After filing B, they still produce 5 beats/sec. Frequency of B is:", options: ["507 Hz", "512 Hz", "517 Hz", "500 Hz"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-13", subject: "Physics", text: "The blue color of sea is due to:", options: ["reflection of light from sea water", "diffraction of light from sea water", "refraction of light from sea water", "scattering of light by sea water"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-14", subject: "Physics", text: "The principle of which device is based on dispersion without deviation:", options: ["Chromatic doublet", "Achromatic doublet", "Spectrometer", "Direct vision spectroscope"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-15", subject: "Physics", text: "Magnetic moment of a magnet decreases by 19%, then the time period:", options: ["increases by 10%", "decreases by 10%", "increases by 20%", "decreases by 20%"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-16", subject: "Physics", text: "A charge q₁ exerts force on q₂. If a third charge q₃ is brought near, the force q₁ exerts on q₂:", options: ["increases", "decreases", "remains constant", "depends on sign of charge"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-17", subject: "Physics", text: "Magnetic susceptibility is negative for:", options: ["diamagnetic", "paramagnetic", "ferromagnetic", "all"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-18", subject: "Physics", text: "Two heater wires of equal length are connected first in series then in parallel. Ratio of heat produced (series:parallel) is:", options: ["2:1", "1:2", "4:1", "1:4"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-19", subject: "Physics", text: "One sixteenth of initial amount of radioactive isotope remains after 2 hours. The half-life of the isotope is:", options: ["15 min", "45 min", "30 min", "60 min"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-20", subject: "Physics", text: "If r is the radius of the Bohr orbit of H atom, then radius of same orbit of He²⁺ is:", options: ["r", "2r", "r/2", "r/4"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-21", subject: "Physics", text: "Resolving power of the human eye is nearly:", options: ["342", "1/342", "3420", "1/60 of a degree"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-22", subject: "Physics", text: "The luminous efficiency of a lamp is 5 lumen/watt and its luminous intensity is 30 candela. The power of the lamp is:", options: ["6 W", "24 W", "75 W", "150 W"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-23", subject: "Physics", text: "The frequency of radio waves is 15 MHz. What is its wavelength?", options: ["20 m", "15 m", "5 m", "25 m"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-24", subject: "Physics", text: "The sure test of electrification is:", options: ["attraction", "repulsion", "both attraction and repulsion", "neither attraction nor repulsion"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-25", subject: "Physics", text: "The ratio of work done by the battery to energy stored in the capacitor is:", options: ["1:1", "1:2", "2:1", "4:1"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-26", subject: "Physics", text: "Energy stored in magnetic field of 2.5×10⁻³ T is:", options: ["2.48 J/m³", "0.48 J/m³", "3.48 J/m³", "4.48 J/m³"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-27", subject: "Physics", text: "The solar cooker works on the same principle as that of:", options: ["Bolometer", "Pyrometer", "Black body", "Greenhouse effect"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-28", subject: "Physics", text: "The most commonly used semiconductors are:", options: ["germanium and silicon", "germanium and copper", "silicon and glass", "glass and ebonite"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-29", subject: "Physics", text: "The mass of a photon at rest is:", options: ["zero", "1.67×10⁻³⁵ kg", "1 amu", "9×10⁻³¹ kg"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-30", subject: "Physics", text: "If the rest mass of a particle is m₀, its mass when moving at velocity 0.8c is:", options: ["3m₀/5", "5m₀/3", "3m₀/2", "2m₀"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-31", subject: "Physics", text: "The dimensional formula for torque is:", options: ["[MLT⁻²]", "[ML²T⁻²]", "[ML⁻¹T⁻²]", "[ML⁻²T⁻²]"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-32", subject: "Physics", text: "The dot product of two vectors is √3 times the magnitude of their cross product. The angle between them is:", options: ["30°", "45°", "60°", "75°"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-33", subject: "Physics", text: "Frictional force is:", options: ["conservative", "non-conservative", "always constant in magnitude", "always zero"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-34", subject: "Physics", text: "Two solid spheres of equal masses have radii R and 2R. The ratio of their moment of inertia about their tangents will be:", options: ["1:1", "1:4", "1:2", "1:8"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-35", subject: "Physics", text: "A seconds pendulum has time period:", options: ["1 sec", "2 sec", "0.5 sec", "24 hr"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-36", subject: "Physics", text: "A stone is released from a tower. Its total mechanical energy during its fall:", options: ["increases", "decreases", "remains constant", "first increases then becomes constant"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-37", subject: "Physics", text: "The source and sink temperature of a Carnot engine are 400 K and 300 K. What is its efficiency?", options: ["100%", "75%", "33.3%", "25%"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-38", subject: "Physics", text: "The phenomenon of land and sea breeze is a result of:", options: ["conduction", "convection", "radiation", "evaporation"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-39", subject: "Physics", text: "The self-inductance of a straight conductor is:", options: ["zero", "infinity", "very large", "very small"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-40", subject: "Physics", text: "Stationary waves transmit:", options: ["energy", "mass", "momentum", "none of these"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-41", subject: "Physics", text: "What reduces systematic errors in a measurement?", options: ["timing 20 oscillations instead of 1", "measuring diameter at different points and averaging", "reducing parallax using a mirror", "zeroing the instrument before use"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-42", subject: "Physics", text: "Focal length of objective of a telescope is 60 cm. For magnification of 20 (relaxed eye), the length of telescope should be:", options: ["80 cm", "40 cm", "63 cm", "57 cm"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-p-43", subject: "Physics", text: "If a unit charge is taken from one point to another over an equipotential surface, then:", options: ["work is done on the charge", "work is done by the charge", "work done is constant", "no work is done"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-p-44", subject: "Physics", text: "8 small drops each of capacitance C and radius r combine to form a big drop of radius R. The capacitance of the big drop will be:", options: ["2C", "4C", "8C", "16C"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-45", subject: "Physics", text: "The emf of a source doing 5 J of work to move 10 C charge is:", options: ["0.5 V", "2 V", "6 V", "4 V"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-46", subject: "Physics", text: "Area of hysteresis curve indicates:", options: ["retentivity", "loss of energy per cycle", "coercivity", "all of the above"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-47", subject: "Physics", text: "If kinetic energy of a free electron doubles, its de-Broglie wavelength changes by factor:", options: ["√2", "1/√2", "2", "1/2"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-48", subject: "Physics", text: "Radioactivity is the phenomenon associated with the decay of:", options: ["molecules", "nuclei", "transmission of radio waves", "atomic electrons"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-p-49", subject: "Physics", text: "The device which converts AC into DC is called:", options: ["rectifier", "oscillator", "amplifier", "modulator"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-p-50", subject: "Physics", text: "According to Bohr's theory, the relation between principal quantum number n and radius r of orbit is:", options: ["r ∝ 1/n", "r ∝ n", "r ∝ n²", "r ∝ 1/n²"], correctIndex: 2, difficulty: "medium", marks: 1 },

  // ── Chemistry (50) ──
  { id: "cee-c-1", subject: "Chemistry", text: "The structure of H₂O₂ is:", options: ["planar", "non-planar", "spherical", "linear"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-2", subject: "Chemistry", text: "Which statement is wrong for gases?", options: ["Gases do not have definite shape and volume", "Gases are highly compressible", "Confined gas exerts uniform pressure on walls", "Mass of gas cannot be determined by weighing its container"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-3", subject: "Chemistry", text: "In an endothermic reaction the value of ΔH is:", options: ["zero", "positive", "negative", "constant"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-4", subject: "Chemistry", text: "In S(s) + 3/2 O₂ → SO₃ + 2x kcal and SO₂ + ½O₂ → SO₃ + y kcal, the heat of formation of SO₂ is:", options: ["x+y", "x-y", "2x+y", "2x-y"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-5", subject: "Chemistry", text: "Which has maximum electronegativity?", options: ["Cl", "Br", "I", "F"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-6", subject: "Chemistry", text: "The most appropriate method to separate para- and ortho-nitrophenol (1:1 mixture) is:", options: ["distillation", "crystallisation", "vaporisation", "colour spectrum"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-7", subject: "Chemistry", text: "Purification of aluminium by electrolytic refining is:", options: ["Hall's process", "Bayer's process", "Hoope's process", "Serpeck's process"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-8", subject: "Chemistry", text: "Bell-metal is:", options: ["Cu + Pb", "Cu + Sn", "Cu + Zn", "Cu + Ni"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-9", subject: "Chemistry", text: "Which form of phosphorus is most reactive?", options: ["Red", "White", "Scarlet", "Violet"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-10", subject: "Chemistry", text: "Cassiterite is the ore of:", options: ["Mn", "Ni", "Sb", "Sn"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-11", subject: "Chemistry", text: "One mole of ideal gas at 300 K expanded isothermally from 1 L to 10 L. Change in internal energy is:", options: ["163.7 cal", "zero", "1381.1 cal", "9 L·atm"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-12", subject: "Chemistry", text: "Activation energy of a reaction can be determined by:", options: ["evaluating rate constant at standard temperature", "evaluating velocity at two different temperatures", "evaluating rate constant at two different temperatures", "changing concentration of reactant"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-13", subject: "Chemistry", text: "Which is used in preparation of chlorine?", options: ["only MnO₂", "only KMnO₄", "both MnO₂ and KMnO₄", "either MnO₂ or KMnO₄"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-14", subject: "Chemistry", text: "Percentage of lead in a lead pencil is:", options: ["0%", "20%", "70%", "80%"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-15", subject: "Chemistry", text: "When acetylene is passed through dilute H₂SO₄ in presence of HgSO₄, the compound formed is:", options: ["ether", "ketone", "acetic acid", "acetaldehyde"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-16", subject: "Chemistry", text: "Solubility of CaF₂ is 2×10⁻⁴ mol/L. Its solubility product is:", options: ["12×10⁻⁹", "14×10⁻⁹", "22×10⁻¹¹", "32×10⁻¹²"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-17", subject: "Chemistry", text: "The number of atoms in 4.25 g of NH₃ is approximately:", options: ["1×10²³", "2×10²³", "4×10²³", "6×10²³"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-18", subject: "Chemistry", text: "Isomer of ethanol is:", options: ["methanol", "dimethyl ether", "propanol", "acetaldehyde"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-19", subject: "Chemistry", text: "Ethyl chloride is converted to diethyl ether; the reaction is:", options: ["Wurtz reaction", "Grignard reaction", "Perkin's reaction", "Williamson's reaction"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-20", subject: "Chemistry", text: "Denaturation does not affect:", options: ["quaternary structure", "secondary structure", "primary structure", "tertiary structure"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-21", subject: "Chemistry", text: "In Friedel-Crafts alkylation, besides AlCl₃ the other reagents are:", options: ["C₆H₆ + NH₂", "C₆H₆ + CH₄", "C₆H₆ + CH₃Cl", "C₆H₆ + CH₃COCl"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-22", subject: "Chemistry", text: "Phenyl isocyanide is prepared by which reaction?", options: ["Rosenmund's", "Carbylamine", "Reimer-Tiemann", "Wurtz"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-23", subject: "Chemistry", text: "Which is the sweetest sugar?", options: ["sucrose", "glucose", "fructose", "maltose"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-24", subject: "Chemistry", text: "Aldol condensation will not take place in:", options: ["HCHO", "CH₃CHO", "CH₃COCH₃", "CH₃CH₂CHO"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-25", subject: "Chemistry", text: "Organic compound with C=40%, H=13.33%, N=46.67%; its empirical formula is:", options: ["C₂H₇N₂", "CH₅N", "CH₄N", "C₂H₇N"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-26", subject: "Chemistry", text: "Gammexane is:", options: ["chlorobenzene", "benzyl chloride", "bromobenzene", "benzene hexachloride"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-27", subject: "Chemistry", text: "Reaction of ethylene oxide with RMgX leads to formation of:", options: ["RCHOHR", "RCHOHCH₃", "RCH₂CH₂OH", "none"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-28", subject: "Chemistry", text: "Iodoform test is not given by:", options: ["2-pentanone", "ethanol", "ethanal", "3-pentanone"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-29", subject: "Chemistry", text: "Amide is converted into amine by a reaction named:", options: ["Perkin", "Claisen", "Hofmann", "Kekule"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-30", subject: "Chemistry", text: "Natural rubber is the polymer of:", options: ["butadiene", "ethyne", "styrene", "isoprene"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-31", subject: "Chemistry", text: "Radius of an atomic nucleus is in the order of:", options: ["10⁻⁸ cm", "10⁻¹⁰ cm", "10⁻¹² cm", "10⁻¹³ cm"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-c-32", subject: "Chemistry", text: "Which has maximum average velocity at constant temperature?", options: ["CO", "SO₃", "Ne", "O₂"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-33", subject: "Chemistry", text: "An edge atom of a cube provides how many atoms to the unit cell?", options: ["1/8", "1/4", "1/3", "1"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-34", subject: "Chemistry", text: "In most stable elements the number of protons and neutrons is:", options: ["even-even", "even-odd", "odd-even", "odd-odd"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-35", subject: "Chemistry", text: "Which is a pseudo halide?", options: ["PO₄³⁻", "CN⁻", "HF", "CuCl₃"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-36", subject: "Chemistry", text: "According to Fajans rule, covalent bond is favoured by:", options: ["small cation & large anion", "large cation & small anion", "large cation & large anion", "small cation & small anion"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-37", subject: "Chemistry", text: "Strongest reducing agent in solution is:", options: ["Li", "Na", "K", "Cs"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-38", subject: "Chemistry", text: "H₃BO₃ is:", options: ["monobasic and weak Lewis acid", "monobasic and strong Lewis acid", "tribasic and weak Bronsted acid", "monobasic and weak Bronsted acid"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-39", subject: "Chemistry", text: "If same amount of electricity deposits 2.5 g of Ag, the amount of Cu deposited is:", options: ["7.292 g", "0.7292 g", "0.0729 g", "0.00729 g"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-40", subject: "Chemistry", text: "Among noble gases, only Xenon forms stable compounds with fluorine because of:", options: ["low ionisation potential of Xe", "large size of Xe", "higher heat of vaporisation", "higher vapour density"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-41", subject: "Chemistry", text: "The chemical equilibrium of a reversible reaction is not influenced by:", options: ["catalyst", "pressure", "temperature", "concentration"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-42", subject: "Chemistry", text: "In monatomic gases, ratio of specific heat at constant pressure to that at constant volume is:", options: ["1.40", "1.67", "1.33", "1.28"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-43", subject: "Chemistry", text: "Atmospheric pollution is measured in:", options: ["mol/L", "g/L", "ppm", "gm"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-44", subject: "Chemistry", text: "Zn displaces Cu because:", options: ["Zinc has more negative reduction potential than copper", "Copper has more negative reduction potential than Zinc", "Zinc is more electronegative", "Zinc is lower than hydrogen"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-45", subject: "Chemistry", text: "Number of moles of NaOH required to prepare 4.5 litres of 1.5 M solution is:", options: ["6.75", "0.33", "0.3", "67.5"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-46", subject: "Chemistry", text: "IUPAC name of urea is:", options: ["amino amine", "amino methanamide", "1,2-diamino acid", "diaminomethanal"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-47", subject: "Chemistry", text: "Steel contains:", options: ["Fe + C + Mn", "Fe + C + Al", "Fe + Mn", "Fe + Mn + Cr"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-c-48", subject: "Chemistry", text: "Matte contains mainly:", options: ["Fe", "Cu₂S", "Cu₂S and FeS", "CuS and Fe₂S₃"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-c-49", subject: "Chemistry", text: "Sodium is commercially obtained by electrolysis of fused NaCl. The process is called:", options: ["Castner process", "Down's process", "Kellner process", "Solvay process"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-c-50", subject: "Chemistry", text: "Compound X reacts with AgNO₃ giving white ppt and with H₂SO₄ giving white ppt. X is:", options: ["Ba(NO₃)₂", "BaCl₂", "Pb(NO₃)₂", "CuCl₂"], correctIndex: 1, difficulty: "medium", marks: 1 },

  // ── Botany (40) ──
  { id: "cee-b-1", subject: "Botany", text: "Columella is found in the fruiting body of:", options: ["Agaricus", "Mucor", "Lichen", "Marchantia"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-2", subject: "Botany", text: "Which of the following is a true nut?", options: ["Walnut", "Cashewnut", "Groundnut", "Areca nut"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-3", subject: "Botany", text: "Verticillaster type of inflorescence is found in:", options: ["Euphorbia", "Ocimum", "Callistemon", "Achyranthus"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-4", subject: "Botany", text: "The cork in dicot is derived from:", options: ["phellogen", "phelloderm", "periderm", "phellem"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-5", subject: "Botany", text: "Nepenthes is:", options: ["consumer", "primary consumer", "producer and primary consumer", "none"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-6", subject: "Botany", text: "Nostoc belongs to:", options: ["Chlorophyceae", "Cyanophyceae", "Rhodophyceae", "Phaeophyceae"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-7", subject: "Botany", text: "A cross between a homozygous recessive and its hybrid is called:", options: ["back cross", "test cross", "monohybrid cross", "dihybrid cross"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-8", subject: "Botany", text: "The functional unit of the Golgi complex is:", options: ["cristae", "cisternae", "thylakoid", "archiplasm"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-9", subject: "Botany", text: "Fungi Imperfecti (Deuteromycetes) lack:", options: ["hyphae", "spores", "asexual reproduction", "sexual reproduction"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-b-10", subject: "Botany", text: "Quiescent centre is present in:", options: ["root apex", "shoot apex", "vegetative apex", "reproductive phase"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-11", subject: "Botany", text: "During conversion of pyruvic acid to Acetyl-CoA, how many CO₂ molecules are produced?", options: ["three", "one", "four", "two"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-12", subject: "Botany", text: "Parmelia lichens are used to cure:", options: ["whooping cough", "cancer", "diarrhoea", "epilepsy"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-b-13", subject: "Botany", text: "A genetically dwarf plant can be made tall by treating with:", options: ["gibberellic acid", "cytokinin", "auxin", "anti-gibberellin"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-14", subject: "Botany", text: "Advancement in genetic engineering is possible due to:", options: ["oncogene", "exonuclease", "endonuclease", "ligases"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-15", subject: "Botany", text: "The Calvin cycle takes place in:", options: ["thylakoid", "stroma", "cytoplasm", "mitochondria"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-16", subject: "Botany", text: "Which plant has the largest leaf?", options: ["Victoria amazonica", "Rafflesia", "Eucalyptus", "Tectona"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-17", subject: "Botany", text: "Companion cells are associated with:", options: ["xylem vessels", "sieve tubes", "tracheids", "root hairs"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-18", subject: "Botany", text: "Spindle fibre is made up of:", options: ["actin", "myosin", "tubulin", "collagen"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-19", subject: "Botany", text: "Which of the following is used as a biofertilizer?", options: ["Rhizobium", "E. coli", "Penicillium", "Aspergillus"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-20", subject: "Botany", text: "Totipotency refers to the ability of a cell to:", options: ["divide indefinitely", "develop into a complete organism", "produce gametes", "resist pathogens"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-21", subject: "Botany", text: "The process of imbibition involves absorption of:", options: ["minerals", "water", "light", "CO₂"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-22", subject: "Botany", text: "Which tissue is responsible for secondary growth?", options: ["apical meristem", "lateral meristem", "intercalary meristem", "ground meristem"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-23", subject: "Botany", text: "Abscisic acid promotes:", options: ["cell division", "cell elongation", "stomatal opening", "stomatal closure"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-b-24", subject: "Botany", text: "The main pigment for photosynthesis is:", options: ["carotene", "xanthophyll", "chlorophyll a", "chlorophyll b"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-25", subject: "Botany", text: "In angiosperms, the endosperm is:", options: ["haploid", "diploid", "triploid", "tetraploid"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-26", subject: "Botany", text: "Lichens are best indicators of:", options: ["water pollution", "air pollution", "soil pollution", "noise pollution"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-27", subject: "Botany", text: "Which element is essential for the opening and closing of stomata?", options: ["nitrogen", "potassium", "phosphorus", "calcium"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-28", subject: "Botany", text: "The universal recipient blood group is:", options: ["A", "B", "AB", "O"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-29", subject: "Botany", text: "Pollination by wind is called:", options: ["entomophily", "anemophily", "hydrophily", "ornithophily"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-30", subject: "Botany", text: "The crossing over takes place during:", options: ["leptotene", "zygotene", "pachytene", "diplotene"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-31", subject: "Botany", text: "Ozone layer is present in:", options: ["troposphere", "stratosphere", "mesosphere", "thermosphere"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-32", subject: "Botany", text: "Niche of an organism refers to:", options: ["its habitat only", "its feeding habit only", "its role in ecosystem", "its body structure"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-33", subject: "Botany", text: "Multiparous cyme inflorescence axis is found in:", options: ["Calotropis", "Jasmine", "Solanum", "Acacia"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-34", subject: "Botany", text: "Atropa belladonna belongs to:", options: ["Liliaceae", "Brassicaceae", "Solanaceae", "Poaceae"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-b-35", subject: "Botany", text: "Pollen grain is a:", options: ["megaspore", "microsporophyll", "microsporangium", "microspore"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-b-36", subject: "Botany", text: "Highest value of water potential is:", options: ["1.0", "0.0", "10.0", "−1.0"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-b-37", subject: "Botany", text: "Which is common between aerobic and anaerobic respiration?", options: ["TCA/Krebs cycle", "ETS", "Photo-oxidation", "EMP cycle/Glycolysis"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-b-38", subject: "Botany", text: "Energy enters an ecosystem through:", options: ["producer", "primary consumer", "secondary consumer", "tertiary consumer"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-39", subject: "Botany", text: "The rate at which light energy is converted into chemical energy is:", options: ["gross primary productivity", "net primary productivity", "net secondary productivity", "gross secondary productivity"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-b-40", subject: "Botany", text: "Tea is a good stimulant due to the presence of:", options: ["morphine", "ephedrine", "nicotine", "caffeine"], correctIndex: 3, difficulty: "medium", marks: 1 },

  // ── Zoology (40) ──
  { id: "cee-z-1", subject: "Zoology", text: "The two strands of DNA helix are:", options: ["neutral", "one positive and one negative", "positive", "negative"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-2", subject: "Zoology", text: "Photosynthesis is fastest in:", options: ["blue light", "sunlight/intermittent light", "red light", "green light"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-3", subject: "Zoology", text: "Peristalsis is a characteristic movement of:", options: ["cardiac muscle", "skeletal muscle", "smooth muscle", "voluntary muscle"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-4", subject: "Zoology", text: "The hormone responsible for fight or flight response is:", options: ["insulin", "adrenaline", "thyroxine", "oxytocin"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-5", subject: "Zoology", text: "Spermatogenesis takes place in:", options: ["seminal vesicle", "prostate gland", "seminiferous tubules", "epididymis"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-6", subject: "Zoology", text: "The largest gland in the human body is:", options: ["pancreas", "liver", "thyroid", "adrenal"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-7", subject: "Zoology", text: "Which blood cells are responsible for immunity?", options: ["RBC", "WBC", "platelets", "plasma"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-8", subject: "Zoology", text: "The fluid-filled space in a Graafian follicle is called:", options: ["antrum", "corpus luteum", "zona pellucida", "theca"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-z-9", subject: "Zoology", text: "Which of the following is a vestigial organ in humans?", options: ["pancreas", "appendix", "thymus", "spleen"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-10", subject: "Zoology", text: "The phylum Echinodermata is characterised by:", options: ["bilateral symmetry", "radial symmetry", "no symmetry", "both radial and bilateral"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-11", subject: "Zoology", text: "Which type of RNA carries amino acids to the ribosome?", options: ["mRNA", "rRNA", "tRNA", "hnRNA"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-12", subject: "Zoology", text: "Homeostasis refers to:", options: ["body temperature regulation only", "maintaining a stable internal environment", "digestion of food", "immune response"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-13", subject: "Zoology", text: "The enzyme that unwinds DNA during replication is:", options: ["ligase", "helicase", "polymerase", "primase"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-14", subject: "Zoology", text: "Insulin is produced by which cells of the pancreas?", options: ["alpha cells", "beta cells", "delta cells", "acinar cells"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-15", subject: "Zoology", text: "Henle's loop is a part of:", options: ["nephron", "neuron", "lung", "liver"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-z-16", subject: "Zoology", text: "Assertion: Earthworms are called farmer's friends. Reason: They make the soil loose.", options: ["Both A and R are true and R explains A", "Both A and R are true but R does not explain A", "A is true but R is false", "A is false but R is true"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-z-17", subject: "Zoology", text: "Double fertilisation occurs in:", options: ["gymnosperms", "angiosperms", "bryophytes", "pteridophytes"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-18", subject: "Zoology", text: "The genetic material in HIV is:", options: ["single stranded DNA", "double stranded DNA", "single stranded RNA", "double stranded RNA"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-19", subject: "Zoology", text: "Blood pressure is measured by:", options: ["sphygmomanometer", "manometer", "barometer", "galvanometer"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-z-20", subject: "Zoology", text: "Which part of the brain controls body temperature?", options: ["cerebellum", "medulla oblongata", "hypothalamus", "cerebrum"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-21", subject: "Zoology", text: "Fertilisation in humans takes place in:", options: ["uterus", "ovary", "fallopian tube", "vagina"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-22", subject: "Zoology", text: "The function of the epiglottis is to:", options: ["produce sound", "prevent food entering trachea", "filter air", "produce mucus"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-23", subject: "Zoology", text: "Haemoglobin contains which metal?", options: ["copper", "zinc", "iron", "magnesium"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-24", subject: "Zoology", text: "Synapsis occurs during:", options: ["leptotene", "zygotene", "pachytene", "diplotene"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-25", subject: "Zoology", text: "The process by which organisms maintain water balance is called:", options: ["osmoregulation", "thermoregulation", "excretion", "digestion"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-z-26", subject: "Zoology", text: "Corpus callosum connects:", options: ["cerebrum and cerebellum", "two cerebral hemispheres", "brain and spinal cord", "thalamus and hypothalamus"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-27", subject: "Zoology", text: "The protein found in muscles is:", options: ["keratin", "collagen", "actin", "fibrin"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-28", subject: "Zoology", text: "The SA node is located in:", options: ["left atrium", "right atrium", "left ventricle", "right ventricle"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-29", subject: "Zoology", text: "Malaria is caused by:", options: ["Plasmodium vivax", "Entamoeba histolytica", "Leishmania donovani", "Trypanosoma"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-z-30", subject: "Zoology", text: "The contractile protein in muscle is:", options: ["tubulin", "actin and myosin", "keratin", "collagen"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-31", subject: "Zoology", text: "Rennin is an enzyme secreted in:", options: ["stomach", "pancreas", "small intestine", "liver"], correctIndex: 0, difficulty: "medium", marks: 1 },
  { id: "cee-z-32", subject: "Zoology", text: "The yellow colour of urine is due to:", options: ["urea", "urochrome", "uric acid", "creatinine"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-33", subject: "Zoology", text: "Kupffer cells are found in:", options: ["kidney", "liver", "spleen", "lung"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-34", subject: "Zoology", text: "The hardest substance in the human body is:", options: ["bone", "cartilage", "enamel", "dentine"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-35", subject: "Zoology", text: "A bacteriophage attacks:", options: ["plants", "bacteria", "fungi", "animals"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-36", subject: "Zoology", text: "The scientific name of human is:", options: ["Homo erectus", "Homo habilis", "Homo sapiens", "Homo neanderthalensis"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-37", subject: "Zoology", text: "The immune antibodies are:", options: ["lipids", "carbohydrates", "proteins", "nucleic acids"], correctIndex: 2, difficulty: "medium", marks: 1 },
  { id: "cee-z-38", subject: "Zoology", text: "Amniocentesis is used to detect:", options: ["sex of foetus", "chromosomal abnormalities", "metabolic disorders", "all of the above"], correctIndex: 3, difficulty: "medium", marks: 1 },
  { id: "cee-z-39", subject: "Zoology", text: "The number of pairs of cranial nerves in humans is:", options: ["10", "12", "31", "8"], correctIndex: 1, difficulty: "medium", marks: 1 },
  { id: "cee-z-40", subject: "Zoology", text: "Which part of the nephron is impermeable to water?", options: ["proximal convoluted tubule", "descending limb of Henle's loop", "ascending limb of Henle's loop", "distal convoluted tubule"], correctIndex: 2, difficulty: "medium", marks: 1 },
];

// ─── Mock Tests ──────────────────────────────────────────────────────────────
const CEE_PHYSICS    = CEE_QUESTIONS.filter((q) => q.subject === "Physics");
const CEE_CHEMISTRY  = CEE_QUESTIONS.filter((q) => q.subject === "Chemistry");
const CEE_BOTANY     = CEE_QUESTIONS.filter((q) => q.subject === "Botany");
const CEE_ZOOLOGY    = CEE_QUESTIONS.filter((q) => q.subject === "Zoology");

export const MOCK_TESTS: MockTest[] = [
  // IOE
  {
    id: "ioe-full-1",
    exam: "IOE",
    title: "IOE Full Mock Test — Set 1",
    mode: "full",
    difficulty: "mixed",
    durationMinutes: 30,
    questions: IOE_QUESTIONS,
  },
  {
    id: "ioe-physics-1",
    exam: "IOE",
    title: "IOE Physics — Practice Set 1",
    mode: "subject",
    subject: "Physics",
    difficulty: "easy",
    durationMinutes: 15,
    questions: IOE_QUESTIONS.filter((q) => q.subject === "Physics"),
  },
  // CEE
  {
    id: "cee-full-1",
    exam: "CEE",
    title: "CEE Full Mock Test — Set 1",
    mode: "full",
    difficulty: "mixed",
    durationMinutes: 180,
    questions: CEE_QUESTIONS,
  },
  {
    id: "cee-physics-1",
    exam: "CEE",
    title: "CEE Physics — Practice Set 1",
    mode: "subject",
    subject: "Physics",
    difficulty: "medium",
    durationMinutes: 60,
    questions: CEE_PHYSICS,
  },
  {
    id: "cee-chemistry-1",
    exam: "CEE",
    title: "CEE Chemistry — Practice Set 1",
    mode: "subject",
    subject: "Chemistry",
    difficulty: "medium",
    durationMinutes: 60,
    questions: CEE_CHEMISTRY,
  },
  {
    id: "cee-botany-1",
    exam: "CEE",
    title: "CEE Botany — Practice Set 1",
    mode: "subject",
    subject: "Botany",
    difficulty: "medium",
    durationMinutes: 45,
    questions: CEE_BOTANY,
  },
  {
    id: "cee-zoology-1",
    exam: "CEE",
    title: "CEE Zoology — Practice Set 1",
    mode: "subject",
    subject: "Zoology",
    difficulty: "medium",
    durationMinutes: 45,
    questions: CEE_ZOOLOGY,
  },
];

export function getTestById(id: string): MockTest | undefined {
  return MOCK_TESTS.find((t) => t.id === id);
}

export function getTestsByExam(exam: "IOE" | "CEE"): MockTest[] {
  return MOCK_TESTS.filter((t) => t.exam === exam);
}

export function getQuestionsBySubject(exam: "IOE" | "CEE", subject: string): Question[] {
  const allQ = exam === "CEE" ? CEE_QUESTIONS : IOE_QUESTIONS;
  return allQ.filter((q) => q.subject === subject);
}
